name: Update environment

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: sudo gem install bundler:1.17.1
    
    - name: update gems
      run: sudo bundle update --bundler

        
